# Generated by Django 5.2.9 on 2025-12-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Телеграм chat-id"
            ),
        ),
    ]
