# Generated by Django 5.2.9 on 2025-12-08 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(max_length=150, verbose_name="Место привычки"),
                ),
                ("time", models.TimeField(verbose_name="Время выполнения привычки")),
                (
                    "description",
                    models.CharField(max_length=150, verbose_name="Описание привычки"),
                ),
                (
                    "pleasant_habit",
                    models.BooleanField(verbose_name="Полезная привычка"),
                ),
                (
                    "period",
                    models.IntegerField(
                        verbose_name="Периодичность выполнения привычки в днях"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Вознаграждение за выполнение привычки",
                    ),
                ),
                (
                    "time_complete",
                    models.IntegerField(
                        verbose_name="Время на выполнение привычки в секундах"
                    ),
                ),
                ("public", models.BooleanField(verbose_name="Признак публичности")),
                (
                    "associated_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": [
                    "owner",
                    "place",
                    "time",
                    "description",
                    "pleasant_habit",
                    "associated_habit",
                    "period",
                    "time_complete",
                    "public",
                ],
            },
        ),
    ]
